name: rick_and_morty
description: Test task Rick and Morty.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  injectable_generator: ^2.1.6
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  mobx: ^2.2.0
  mobx_codegen: ^2.3.0
  path_provider: ^2.0.15
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1


dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.2

flutter:
  uses-material-design: true
